# Site settings

title: Project Pages
header-img: img/home-bg.jpg
email: darrenmm33@gmail.com
description: "This is my first test!!"
baseurl: "/project-pages"
url: "http://matin-hub.github.io"
github_username:  darrenm13
project_repository: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
