# Site settings

title: Crystal Placticy Codes
header-img: img/home-bg.jpg
email: darrenmm33@gmail.com
description: "Matching crystal placticity codes"
baseurl: "/Test1"
url: "http://darrenm13.github.io"
github_username:  darrenm13
project_repository: MinedProjects

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
